### ISSUE TITLE
Add state management

### ISSUE THREAD

**Issue by zvikarp** [capslock-bmdc/daf_plus_plus#42]
First time for me, never done it but it is needed for this project to store dates, firebase update counter and probably other stuff. I heard good stuff about provider but not locked on anything yet.

**Comment by chaimgross** [comment]
Not sure what your referring to

**Comment by zvikarp** [comment]
https://flutter.dev/docs/development/data-and-backend/state-mgmt/simple

**Comment by zvikarp** [comment]
to fix before closing:

- [ ] save last daf
- [ ] backup to filrestore
- [ ] daf yomi full page list
