### ISSUE TITLE
hebrew dates

### ISSUE THREAD

**Issue by zvikarp** [capslock-bmdc/daf_plus_plus#49]
or what about hebrew dates? or let the user choose?
is there a simple plug&play extension for hebrew dates?
if not learning the daf yomi, do we still display the dates (or do we ask the user that too)?

my opinion is to have a dropdown in setting with the options [english dates (in HE, and EN, depending on lang settings), hebrew dates  (in HE, and EN, depending on lang settings), no dates] and by default it would be set to english dates.

**Comment by chaimgross** [comment]
plug and play would probably have to be a flutter based one, no? So we can look for one but I doubt it exists... 
if we can figure out how to get then ya we can do something like that

**Comment by zvikarp** [comment]
so currently we are displaying english dates in hebrew, but not hebrew dates. this can wait for when we have some extra time...

**Comment by zvikarp** [comment]
https://github.com/yakir8/kosher_dart
